language: go
go:
- 1.19.x
addons:
  apt:
    packages:
    - debhelper
    - fakeroot
    - bash-completion
env:
  global:
  - V=1
before_script:
- make bootstrap
script:
- make
- make artifacts
after_success:
- bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN" || echo "Codecov did
  not collect coverage reports"
notifications:
  email: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "sqhHKjYYVnaUAvfvwh3XFNMCm9i7I1w4RDv91OJLPJ1yvoTn0Jm2RJMI/kN+3m448OrbEdCF2c3NMy3CUD2tkItCmqznnEj3iMlhcWUHPc74UM0/mIxg9OAk48PKI/ntflmf3vinXvLwp8wmDM19s3m4lPceipG4T6mJg0IVVq9tzLsSJlyJcG/iQin5ib1w4q4BJ6fWW2M6pyKRyeSihoc+zDAL/H1SnGFyygJ79R4dzyUYMOOWDUbrf3IyvbTwxb4wyAUncUafYcKFql8N2rQzoWQ/i2vhSKkx+rz+6AY0QsZk5XZhlvKe/Zc3PIM6aZo0Vr9bDCIYZElrHC4yeqp1gE6oQd2KAD+jcFDKKV1PtwgS1EPkQJVrs+snBabiqJ4FAW0cIthV6rrKxSso28OPnifVM+gdS+4tBQNprICdgDyDeLQPasiPJp0GJbygjbAgA396hGiNEcJ0V/I4BhDac2kcYIIxXFIHQGYoC6MPrce90voufJi22AtGbnM4i2rbYeMy9jQzXYvXws/ZIAbJY/M5ftklwOlEFQVDDTLAB8i4X5GtlgGYR9hzvI2hA/RXWdhvPq8lw/NXOP2dcstpT2DPPHOdJpg8X9zlaGmv2OHCJCHg7nFPxeF6vlCPnjV44NRh4b3mtVDvWqbtbHk3qGY/dzhQ6POXAOZqbJg="
  file_glob: true
  file: ".travis-releases/*"
  on:
    repo: smallstep/step-sds
    tags: true
