language: go
go:
- 1.19.x
addons:
  apt:
    packages:
    - debhelper
    - fakeroot
    - bash-completion
env:
  global:
  - V=1
before_script:
- make bootstrap
script:
- make
- make artifacts
after_success:
- bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN" || echo "Codecov did
  not collect coverage reports"
notifications:
  email: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "vlJF1B/h04AhCkISmG8ulGrZKcsf3Xs2BMuXLEIPtNHBb7TdwhenKoKdUeAC/v9tZwLk2tqnV0s8YIoluDefH13J8smBCwdVr3J2nJl+6jJZyjc1j1W7XHIkcODupzJcU1NSM71JENn4FwLet61DkFO/Z3peREe9ArJMFLlgzDrPDvxHjgCRL2mN1stpnR9Lms1hSN7MIDMlCyms2dOXHD3vm8S3OUmokRXxXLgs0V2OFkNn46Ynxp2kD5LXNHMuNoarqdN60EVb2KQFCFx9SzeSMQP0Vtq9HXGq0RM4bMkC8w3lud+RyknVYFiy5KMS5iSCus0i3VayzwXkVuK1hn4afKzFhZZBje+eCv1JujHFMch0O5Ht3X7USF8tKMgbBLtEhjuFO6cvHV2+fBD8aHKe59N8pJtncf5r0apehKJdhvUq4oQeUpyrM4z+2VHrxEBrJSKHFolBBRLWeKgV2ck10QBfEoBrygZHjwzpM5B8tx5WjOB3bo4qRA2WiKcRWYxSICrrcgtjKTe4fZ//TJob77znkQQ1nfOSrfdm5CnIXe6eFDeqq+5CNPSU7rzQWq+/SHTiC/DtplCk3khFab1Vk4uXWZVo3OTq+bqX+n4CmuuiLYK4YvQ4hnEj7g0t+PjxEw6D1TjP3/dE1hhJGCXsqYXPYgsacmWwGponXY0="
  file_glob: true
  file: ".travis-releases/*"
  on:
    repo: smallstep/step-sds
    tags: true
